### ISSUE TITLE
Enchancement: backdropMode

### ISSUE THREAD

**Issue by seanaguinaga** [rodydavis/navigation_rail#3]
First of all, thank you again for making this. 

I'm not sure how customizable you want this to be out of the box of if you'd want to support every possible permutation possible/modes mentioned in the docs by default or if you'd want this to make it into Flutters Widget library itself?

To get close the effect below, I had to modify your source files a bit: colors for the rail in a tablet media query size. 

![image](https://user-images.githubusercontent.com/15254340/73594324-29920100-44c2-11ea-8397-9340c3b17b08.png)

Are you open to pull requests adding all of the permutations mentioned in the docs/support for custom or inherited theming for all of these permutations/accessibility features, etc..? 

https://github.com/flutter/flutter/pull/49574

I saw this earlier (just saw you replied)

Eventual goal to maybe submit it as a Material Widget once all bases and things are covered?

Thoughts?

**Comment by rodydavis** [comment]
I’m open to PRs! I can see if there is a way to make a mode in the constructor. Like Switch and Switch.adaptive, completely different behavior and look but same widget.

Where does this spec/design come from?

**Comment by seanaguinaga** [comment]
Okay! Cool!

The material guidelines page: https://material.io/components/navigation-rail/#behavior


Good thinking! (Switch idea)
