### ISSUE TITLE
Rename NavigationRail

### ISSUE THREAD

**Issue by Zazo032** [rodydavis/navigation_rail#7]
Now that Flutter's `material` library has a component named [`NavigationRail`](https://github.com/flutter/flutter/pull/49574), on latest `master`'s channel, when importing both this library and `material`, this error is thrown:

```
error: The name 'NavigationRail' is defined in the libraries 'package:flutter/src/material/navigation_rail.dart (via package:flutter/material.dart)' and 'package:navigation_rail/navigation_rail.dart'. (ambiguous_import at [<elided>])
```

The workaround to make this compatible is changing `material`'s import like this:

```dart
import 'package:flutter/material.dart' hide NavigationRail;
```

The easiest (but breaking) way to solve this is to rename `NavigationRail` or warn about what you should do in order to import both this plugin and `material`.

**Comment by rodydavis** [comment]
Yep that’s what I was planning! Thank you 💪🏻
